Update patch set 1
Patch Set 1:

This causes 296 tests to fail on the Jenkins host building against gerrithub. The problem seen in the first test is:
Felmeddelande
JVMCFRE116 invoke bytecode must reference a Methodref; class=org/argouml/cognitive/ListSet, method=spliterator()Ljava/util/Spliterator;, pc=5 Exception Details:   Location:     org/argouml/cognitive/ListSet.spliterator()Ljava/util/Spliterator; @5: JBinvokespecial   Reason:     Wrong type at the index 14 of constant pool
Stacktrace
java.lang.VerifyError: JVMCFRE116 invoke bytecode must reference a Methodref; class=org/argouml/cognitive/ListSet, method=spliterator()Ljava/util/Spliterator;, pc=5
Exception Details:
  Location:
    org/argouml/cognitive/ListSet.spliterator()Ljava/util/Spliterator; @5: JBinvokespecial
  Reason:
    Wrong type at the index 14 of constant pool
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:730)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
	at org.argouml.cognitive.Critic.<init>(Critic.java:254)
	at org.argouml.cognitive.TestCritic.setUp(TestCritic.java:56)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:74)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

Patch-set: 1
Reviewer: Gerrit User 1016795 <1016795@d5d70762-12d0-45a1-890d-524b12d3f735>